"""initial schema

Revision ID: 39774f94ac35
Revises: 
Create Date: 2026-06-05 04:49:42.705524+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39774f94ac35'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_orgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('github_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id')
    )
    op.create_index(op.f('ix_github_orgs_id'), 'github_orgs', ['id'], unique=False)
    op.create_index(op.f('ix_github_orgs_login'), 'github_orgs', ['login'], unique=True)
    op.create_table('gold_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('os_family', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dockerfile', sa.Text(), nullable=True),
    sa.Column('gitlab_project_id', sa.String(length=255), nullable=True),
    sa.Column('gitlab_project_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gold_images_id'), 'gold_images', ['id'], unique=False)
    op.create_index(op.f('ix_gold_images_name'), 'gold_images', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('keycloak_sub', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_keycloak_sub'), 'users', ['keycloak_sub'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('github_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('github_url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('custom_description', sa.Text(), nullable=True),
    sa.Column('readme_md', sa.Text(), nullable=True),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('homepage_url', sa.String(length=500), nullable=True),
    sa.Column('license_spdx', sa.String(length=100), nullable=True),
    sa.Column('license_name', sa.String(length=255), nullable=True),
    sa.Column('license_text', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_fork', sa.Boolean(), nullable=False),
    sa.Column('stale_threshold_days', sa.Integer(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('github_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('github_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('github_pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['github_orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id')
    )
    op.create_index(op.f('ix_github_projects_full_name'), 'github_projects', ['full_name'], unique=True)
    op.create_index(op.f('ix_github_projects_id'), 'github_projects', ['id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('app_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('gold_image_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dockerfile', sa.Text(), nullable=True),
    sa.Column('gitlab_project_id', sa.String(length=255), nullable=True),
    sa.Column('gitlab_project_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gold_image_id'], ['gold_images.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['github_projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_images_gold_image_id'), 'app_images', ['gold_image_id'], unique=False)
    op.create_index(op.f('ix_app_images_id'), 'app_images', ['id'], unique=False)
    op.create_index(op.f('ix_app_images_name'), 'app_images', ['name'], unique=False)
    op.create_index(op.f('ix_app_images_project_id'), 'app_images', ['project_id'], unique=False)
    op.create_table('github_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('github_release_id', sa.Integer(), nullable=True),
    sa.Column('tag_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_prerelease', sa.Boolean(), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['github_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_release_id')
    )
    op.create_index(op.f('ix_github_releases_id'), 'github_releases', ['id'], unique=False)
    op.create_index(op.f('ix_github_releases_project_id'), 'github_releases', ['project_id'], unique=False)
    op.create_table('gitlab_mirrors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('gitlab_project_id', sa.String(length=255), nullable=True),
    sa.Column('gitlab_namespace', sa.String(length=500), nullable=True),
    sa.Column('gitlab_url', sa.String(length=500), nullable=False),
    sa.Column('gitlab_name', sa.String(length=255), nullable=True),
    sa.Column('pipeline_trigger_token', sa.String(length=255), nullable=True),
    sa.Column('mirrored_branch', sa.String(length=255), nullable=False),
    sa.Column('last_synced_release_tag', sa.String(length=255), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_flag', sa.Integer(), nullable=False),
    sa.Column('status_text', sa.String(length=500), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['github_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gitlab_mirrors_gitlab_project_id'), 'gitlab_mirrors', ['gitlab_project_id'], unique=False)
    op.create_index(op.f('ix_gitlab_mirrors_id'), 'gitlab_mirrors', ['id'], unique=False)
    op.create_index(op.f('ix_gitlab_mirrors_project_id'), 'gitlab_mirrors', ['project_id'], unique=False)
    op.create_table('build_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_type', sa.String(length=10), nullable=False),
    sa.Column('gold_image_id', sa.Integer(), nullable=True),
    sa.Column('app_image_id', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('use_default_schedule', sa.Boolean(), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['app_image_id'], ['app_images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gold_image_id'], ['gold_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_build_schedules_app_image_id'), 'build_schedules', ['app_image_id'], unique=False)
    op.create_index(op.f('ix_build_schedules_gold_image_id'), 'build_schedules', ['gold_image_id'], unique=False)
    op.create_index(op.f('ix_build_schedules_id'), 'build_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_build_schedules_image_type'), 'build_schedules', ['image_type'], unique=False)
    op.create_table('image_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_type', sa.String(length=10), nullable=False),
    sa.Column('gold_image_id', sa.Integer(), nullable=True),
    sa.Column('app_image_id', sa.Integer(), nullable=True),
    sa.Column('version_tag', sa.String(length=255), nullable=False),
    sa.Column('arch', sa.String(length=50), nullable=False),
    sa.Column('registry_url', sa.String(length=500), nullable=True),
    sa.Column('sha256_digest', sa.String(length=255), nullable=True),
    sa.Column('cosign_signature', sa.String(length=1000), nullable=True),
    sa.Column('is_signed', sa.Boolean(), nullable=False),
    sa.Column('status_flag', sa.Integer(), nullable=False),
    sa.Column('status_text', sa.String(length=500), nullable=True),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['app_image_id'], ['app_images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gold_image_id'], ['gold_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_versions_app_image_id'), 'image_versions', ['app_image_id'], unique=False)
    op.create_index(op.f('ix_image_versions_gold_image_id'), 'image_versions', ['gold_image_id'], unique=False)
    op.create_index(op.f('ix_image_versions_id'), 'image_versions', ['id'], unique=False)
    op.create_index(op.f('ix_image_versions_image_type'), 'image_versions', ['image_type'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mirror_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.String(length=255), nullable=True),
    sa.Column('pipeline_url', sa.String(length=500), nullable=True),
    sa.Column('status_flag', sa.Integer(), nullable=False),
    sa.Column('status_text', sa.String(length=500), nullable=True),
    sa.Column('log_output', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mirror_id'], ['gitlab_mirrors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_id'), 'sync_logs', ['id'], unique=False)
    op.create_index(op.f('ix_sync_logs_mirror_id'), 'sync_logs', ['mirror_id'], unique=False)
    op.create_table('sync_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mirror_id', sa.Integer(), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('use_default_schedule', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mirror_id'], ['gitlab_mirrors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_schedules_id'), 'sync_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_sync_schedules_mirror_id'), 'sync_schedules', ['mirror_id'], unique=False)
    op.create_table('build_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_version_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.String(length=255), nullable=True),
    sa.Column('pipeline_url', sa.String(length=500), nullable=True),
    sa.Column('status_flag', sa.Integer(), nullable=False),
    sa.Column('status_text', sa.String(length=500), nullable=True),
    sa.Column('log_output', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['image_version_id'], ['image_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_build_logs_id'), 'build_logs', ['id'], unique=False)
    op.create_index(op.f('ix_build_logs_image_version_id'), 'build_logs', ['image_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_build_logs_image_version_id'), table_name='build_logs')
    op.drop_index(op.f('ix_build_logs_id'), table_name='build_logs')
    op.drop_table('build_logs')
    op.drop_index(op.f('ix_sync_schedules_mirror_id'), table_name='sync_schedules')
    op.drop_index(op.f('ix_sync_schedules_id'), table_name='sync_schedules')
    op.drop_table('sync_schedules')
    op.drop_index(op.f('ix_sync_logs_mirror_id'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_id'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_image_versions_image_type'), table_name='image_versions')
    op.drop_index(op.f('ix_image_versions_id'), table_name='image_versions')
    op.drop_index(op.f('ix_image_versions_gold_image_id'), table_name='image_versions')
    op.drop_index(op.f('ix_image_versions_app_image_id'), table_name='image_versions')
    op.drop_table('image_versions')
    op.drop_index(op.f('ix_build_schedules_image_type'), table_name='build_schedules')
    op.drop_index(op.f('ix_build_schedules_id'), table_name='build_schedules')
    op.drop_index(op.f('ix_build_schedules_gold_image_id'), table_name='build_schedules')
    op.drop_index(op.f('ix_build_schedules_app_image_id'), table_name='build_schedules')
    op.drop_table('build_schedules')
    op.drop_index(op.f('ix_gitlab_mirrors_project_id'), table_name='gitlab_mirrors')
    op.drop_index(op.f('ix_gitlab_mirrors_id'), table_name='gitlab_mirrors')
    op.drop_index(op.f('ix_gitlab_mirrors_gitlab_project_id'), table_name='gitlab_mirrors')
    op.drop_table('gitlab_mirrors')
    op.drop_index(op.f('ix_github_releases_project_id'), table_name='github_releases')
    op.drop_index(op.f('ix_github_releases_id'), table_name='github_releases')
    op.drop_table('github_releases')
    op.drop_index(op.f('ix_app_images_project_id'), table_name='app_images')
    op.drop_index(op.f('ix_app_images_name'), table_name='app_images')
    op.drop_index(op.f('ix_app_images_id'), table_name='app_images')
    op.drop_index(op.f('ix_app_images_gold_image_id'), table_name='app_images')
    op.drop_table('app_images')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_github_projects_id'), table_name='github_projects')
    op.drop_index(op.f('ix_github_projects_full_name'), table_name='github_projects')
    op.drop_table('github_projects')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_keycloak_sub'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_gold_images_name'), table_name='gold_images')
    op.drop_index(op.f('ix_gold_images_id'), table_name='gold_images')
    op.drop_table('gold_images')
    op.drop_index(op.f('ix_github_orgs_login'), table_name='github_orgs')
    op.drop_index(op.f('ix_github_orgs_id'), table_name='github_orgs')
    op.drop_table('github_orgs')
    # ### end Alembic commands ###
