"""initial schema

Revision ID: 37590bb4a2ec
Revises: 
Create Date: 2026-08-16 11:59:01.642053+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37590bb4a2ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('credential_type', sa.Enum('github_token', 'gitlab_token', 'https_basic', 'ssh_key', name='credential_type_enum'), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('encrypted_secret', sa.Text(), nullable=True),
    sa.Column('ssh_public_key', sa.Text(), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('status_flag', sa.Integer(), nullable=False),
    sa.Column('status_text', sa.String(length=500), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_id'), 'credentials', ['id'], unique=False)
    op.create_index(op.f('ix_credentials_name'), 'credentials', ['name'], unique=True)
    op.create_table('github_orgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('github_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id')
    )
    op.create_index(op.f('ix_github_orgs_id'), 'github_orgs', ['id'], unique=False)
    op.create_index(op.f('ix_github_orgs_login'), 'github_orgs', ['login'], unique=True)
    op.create_table('gold_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('os_family', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dockerfile', sa.Text(), nullable=True),
    sa.Column('gitlab_project_id', sa.String(length=255), nullable=True),
    sa.Column('gitlab_project_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gold_images_id'), 'gold_images', ['id'], unique=False)
    op.create_index(op.f('ix_gold_images_name'), 'gold_images', ['name'], unique=True)
    op.create_table('oidc_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer_url', sa.String(length=512), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret', sa.Text(), nullable=True),
    sa.Column('frontend_client_id', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('public_url', sa.String(length=512), nullable=True),
    sa.Column('role_mapping', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oidc_config_id'), 'oidc_config', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('source_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_path', sa.String(length=500), nullable=True),
    sa.Column('web_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_repos', sa.Integer(), nullable=False),
    sa.Column('mirrored_repos', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_groups_id'), 'source_groups', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('keycloak_sub', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_keycloak_sub'), 'users', ['keycloak_sub'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('resource_name', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_table('github_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('github_url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('custom_description', sa.Text(), nullable=True),
    sa.Column('readme_md', sa.Text(), nullable=True),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('homepage_url', sa.String(length=500), nullable=True),
    sa.Column('license_spdx', sa.String(length=100), nullable=True),
    sa.Column('license_name', sa.String(length=255), nullable=True),
    sa.Column('license_text', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_fork', sa.Boolean(), nullable=False),
    sa.Column('stale_threshold_days', sa.Integer(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('github_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('github_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('github_pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['github_orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id')
    )
    op.create_index(op.f('ix_github_projects_full_name'), 'github_projects', ['full_name'], unique=True)
    op.create_index(op.f('ix_github_projects_id'), 'github_projects', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index('ix_teams_owner', 'teams', ['owner_user_id'], unique=False)
    op.create_index('uq_teams_name', 'teams', ['name'], unique=True, postgresql_where=sa.text('is_deleted = false'), sqlite_where=sa.text('is_deleted = false'))
    op.create_table('app_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('gold_image_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dockerfile', sa.Text(), nullable=True),
    sa.Column('gitlab_project_id', sa.String(length=255), nullable=True),
    sa.Column('gitlab_project_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gold_image_id'], ['gold_images.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['github_projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_images_gold_image_id'), 'app_images', ['gold_image_id'], unique=False)
    op.create_index(op.f('ix_app_images_id'), 'app_images', ['id'], unique=False)
    op.create_index(op.f('ix_app_images_name'), 'app_images', ['name'], unique=False)
    op.create_index(op.f('ix_app_images_project_id'), 'app_images', ['project_id'], unique=False)
    op.create_table('github_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('github_release_id', sa.Integer(), nullable=True),
    sa.Column('tag_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_prerelease', sa.Boolean(), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['github_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_release_id')
    )
    op.create_index(op.f('ix_github_releases_id'), 'github_releases', ['id'], unique=False)
    op.create_index(op.f('ix_github_releases_project_id'), 'github_releases', ['project_id'], unique=False)
    op.create_table('resource_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.Enum('git', 'docker', 'helm', name='provider_domain_enum'), nullable=False),
    sa.Column('subtype', sa.Enum('github', 'gitlab', 'generic_git', 'docker_hub', 'quay', 'gcr', 'ecr', 'acr', 'ghcr', 'harbor', 'generic_registry', 'helm_repo', name='provider_subtype_enum'), nullable=False),
    sa.Column('category', sa.Enum('system', 'public', 'private', name='provider_category_enum'), nullable=False),
    sa.Column('visibility', sa.Enum('owner', 'team', 'public', name='provider_visibility_enum'), nullable=False),
    sa.Column('direction', sa.Enum('external', 'internal', name='provider_direction_enum'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_protected', sa.Boolean(), nullable=False),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status_flag', sa.Integer(), nullable=False),
    sa.Column('status_text', sa.String(length=500), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("category != 'private' OR owner_user_id IS NOT NULL", name='ck_resource_providers_private_owner'),
    sa.CheckConstraint("visibility != 'team' OR (team_id IS NOT NULL AND category = 'private')", name='ck_resource_providers_team_visibility'),
    sa.CheckConstraint("visibility != 'team' OR owner_user_id IS NOT NULL", name='ck_resource_providers_team_owner'),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resource_providers_category', 'resource_providers', ['category'], unique=False)
    op.create_index('ix_resource_providers_domain_subtype', 'resource_providers', ['domain', 'subtype'], unique=False)
    op.create_index(op.f('ix_resource_providers_id'), 'resource_providers', ['id'], unique=False)
    op.create_index('ix_resource_providers_owner', 'resource_providers', ['owner_user_id'], unique=False)
    op.create_index('ix_resource_providers_team', 'resource_providers', ['team_id'], unique=False)
    op.create_index('uq_default_per_scope', 'resource_providers', ['domain', 'subtype', 'category', 'direction'], unique=True, postgresql_where=sa.text('is_default = true AND is_deleted = false'), sqlite_where=sa.text('is_default = true AND is_deleted = false'))
    op.create_index('uq_resource_providers_name', 'resource_providers', ['name'], unique=True, postgresql_where=sa.text('is_deleted = false'), sqlite_where=sa.text('is_deleted = false'))
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('role_scope_credentials',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'credential_id')
    )
    op.create_table('role_scope_source_groups',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('source_group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_group_id'], ['source_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'source_group_id')
    )
    op.create_table('team_members',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('lead', 'member', name='team_role_enum'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    op.create_index('ix_team_members_user', 'team_members', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('build_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_type', sa.String(length=10), nullable=False),
    sa.Column('gold_image_id', sa.Integer(), nullable=True),
    sa.Column('app_image_id', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('use_default_schedule', sa.Boolean(), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['app_image_id'], ['app_images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gold_image_id'], ['gold_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_build_schedules_app_image_id'), 'build_schedules', ['app_image_id'], unique=False)
    op.create_index(op.f('ix_build_schedules_gold_image_id'), 'build_schedules', ['gold_image_id'], unique=False)
    op.create_index(op.f('ix_build_schedules_id'), 'build_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_build_schedules_image_type'), 'build_schedules', ['image_type'], unique=False)
    op.create_table('docker_image_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registry_url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('target_provider_id', sa.Integer(), nullable=True),
    sa.Column('gitlab_project_id', sa.String(length=255), nullable=True),
    sa.Column('gitlab_project_url', sa.String(length=500), nullable=True),
    sa.Column('target_registry_url', sa.String(length=500), nullable=True),
    sa.Column('target_project', sa.String(length=255), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_flag', sa.Integer(), nullable=False),
    sa.Column('status_text', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['resource_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_provider_id'], ['resource_providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docker_image_sources_id'), 'docker_image_sources', ['id'], unique=False)
    op.create_index(op.f('ix_docker_image_sources_name'), 'docker_image_sources', ['name'], unique=True)
    op.create_index(op.f('ix_docker_image_sources_provider_id'), 'docker_image_sources', ['provider_id'], unique=False)
    op.create_index(op.f('ix_docker_image_sources_target_provider_id'), 'docker_image_sources', ['target_provider_id'], unique=False)
    op.create_table('gitlab_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('project_path', sa.String(length=512), nullable=False),
    sa.Column('component_path', sa.String(length=512), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('inputs_schema', sa.JSON(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['resource_providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gitlab_components_id'), 'gitlab_components', ['id'], unique=False)
    op.create_index(op.f('ix_gitlab_components_provider_id'), 'gitlab_components', ['provider_id'], unique=False)
    op.create_table('helm_chart_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('gitlab_project_id', sa.String(length=255), nullable=True),
    sa.Column('gitlab_project_url', sa.String(length=500), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_flag', sa.Integer(), nullable=False),
    sa.Column('status_text', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['resource_providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_helm_chart_sources_id'), 'helm_chart_sources', ['id'], unique=False)
    op.create_index(op.f('ix_helm_chart_sources_name'), 'helm_chart_sources', ['name'], unique=True)
    op.create_index(op.f('ix_helm_chart_sources_provider_id'), 'helm_chart_sources', ['provider_id'], unique=False)
    op.create_table('image_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_type', sa.String(length=10), nullable=False),
    sa.Column('gold_image_id', sa.Integer(), nullable=True),
    sa.Column('app_image_id', sa.Integer(), nullable=True),
    sa.Column('version_tag', sa.String(length=255), nullable=False),
    sa.Column('arch', sa.String(length=50), nullable=False),
    sa.Column('registry_url', sa.String(length=500), nullable=True),
    sa.Column('sha256_digest', sa.String(length=255), nullable=True),
    sa.Column('cosign_signature', sa.String(length=1000), nullable=True),
    sa.Column('is_signed', sa.Boolean(), nullable=False),
    sa.Column('status_flag', sa.Integer(), nullable=False),
    sa.Column('status_text', sa.String(length=500), nullable=True),
    sa.Column('vulnerabilities', sa.Integer(), nullable=True),
    sa.Column('vulnerability_severity', sa.String(length=20), nullable=True),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['app_image_id'], ['app_images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gold_image_id'], ['gold_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_versions_app_image_id'), 'image_versions', ['app_image_id'], unique=False)
    op.create_index(op.f('ix_image_versions_gold_image_id'), 'image_versions', ['gold_image_id'], unique=False)
    op.create_index(op.f('ix_image_versions_id'), 'image_versions', ['id'], unique=False)
    op.create_index(op.f('ix_image_versions_image_type'), 'image_versions', ['image_type'], unique=False)
    op.create_table('pipelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('default_variables', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['resource_providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelines_id'), 'pipelines', ['id'], unique=False)
    op.create_index(op.f('ix_pipelines_is_deleted'), 'pipelines', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_pipelines_name'), 'pipelines', ['name'], unique=True)
    op.create_index(op.f('ix_pipelines_provider_id'), 'pipelines', ['provider_id'], unique=False)
    op.create_table('role_scope_providers',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['resource_providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'provider_id')
    )
    op.create_table('source_repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_group_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=500), nullable=False),
    sa.Column('web_url', sa.String(length=500), nullable=True),
    sa.Column('clone_url_https', sa.String(length=500), nullable=True),
    sa.Column('clone_url_ssh', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('stars_count', sa.Integer(), nullable=False),
    sa.Column('forks_count', sa.Integer(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=True),
    sa.Column('license_spdx', sa.String(length=100), nullable=True),
    sa.Column('license_name', sa.String(length=255), nullable=True),
    sa.Column('readme_html', sa.Text(), nullable=True),
    sa.Column('readme_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_release_tag', sa.String(length=255), nullable=True),
    sa.Column('latest_release_name', sa.String(length=255), nullable=True),
    sa.Column('latest_release_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_release_url', sa.String(length=500), nullable=True),
    sa.Column('latest_prerelease_tag', sa.String(length=255), nullable=True),
    sa.Column('latest_prerelease_name', sa.String(length=255), nullable=True),
    sa.Column('latest_prerelease_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_prerelease_url', sa.String(length=500), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_fork', sa.Boolean(), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('discovery_status', sa.Enum('new', 'existing', 'removed', name='discovery_status_enum'), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_flag', sa.Integer(), nullable=False),
    sa.Column('status_text', sa.String(length=500), nullable=True),
    sa.Column('last_commit_sha', sa.String(length=40), nullable=True),
    sa.Column('last_commit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_commit_author', sa.String(length=255), nullable=True),
    sa.Column('last_commit_message', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['resource_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_group_id'], ['source_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_repositories_id'), 'source_repositories', ['id'], unique=False)
    op.create_index(op.f('ix_source_repositories_provider_id'), 'source_repositories', ['provider_id'], unique=False)
    op.create_table('build_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_version_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.String(length=255), nullable=True),
    sa.Column('pipeline_url', sa.String(length=500), nullable=True),
    sa.Column('status_flag', sa.Integer(), nullable=False),
    sa.Column('status_text', sa.String(length=500), nullable=True),
    sa.Column('log_output', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['image_version_id'], ['image_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_build_logs_id'), 'build_logs', ['id'], unique=False)
    op.create_index(op.f('ix_build_logs_image_version_id'), 'build_logs', ['image_version_id'], unique=False)
    op.create_table('docker_image_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.String(length=500), nullable=False),
    sa.Column('tag', sa.String(length=255), nullable=False),
    sa.Column('digest', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('architectures', sa.Text(), nullable=True),
    sa.Column('status_flag', sa.Integer(), nullable=False),
    sa.Column('status_text', sa.String(length=500), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['docker_image_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docker_image_tags_id'), 'docker_image_tags', ['id'], unique=False)
    op.create_index(op.f('ix_docker_image_tags_image_name'), 'docker_image_tags', ['image_name'], unique=False)
    op.create_index(op.f('ix_docker_image_tags_source_id'), 'docker_image_tags', ['source_id'], unique=False)
    op.create_table('docker_sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.String(length=255), nullable=True),
    sa.Column('pipeline_url', sa.String(length=500), nullable=True),
    sa.Column('status_flag', sa.Integer(), nullable=False),
    sa.Column('status_text', sa.String(length=500), nullable=True),
    sa.Column('log_output', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['docker_image_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docker_sync_logs_id'), 'docker_sync_logs', ['id'], unique=False)
    op.create_index(op.f('ix_docker_sync_logs_source_id'), 'docker_sync_logs', ['source_id'], unique=False)
    op.create_table('helm_chart_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('chart_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('app_version', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('digest', sa.String(length=255), nullable=True),
    sa.Column('urls', sa.Text(), nullable=True),
    sa.Column('chart_url', sa.String(length=500), nullable=True),
    sa.Column('gitlab_project_id', sa.String(length=255), nullable=True),
    sa.Column('status_flag', sa.Integer(), nullable=False),
    sa.Column('status_text', sa.String(length=500), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['helm_chart_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_helm_chart_versions_chart_name'), 'helm_chart_versions', ['chart_name'], unique=False)
    op.create_index(op.f('ix_helm_chart_versions_id'), 'helm_chart_versions', ['id'], unique=False)
    op.create_index(op.f('ix_helm_chart_versions_source_id'), 'helm_chart_versions', ['source_id'], unique=False)
    op.create_table('helm_sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.String(length=255), nullable=True),
    sa.Column('pipeline_url', sa.String(length=500), nullable=True),
    sa.Column('status_flag', sa.Integer(), nullable=False),
    sa.Column('status_text', sa.String(length=500), nullable=True),
    sa.Column('log_output', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['helm_chart_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_helm_sync_logs_id'), 'helm_sync_logs', ['id'], unique=False)
    op.create_index(op.f('ix_helm_sync_logs_source_id'), 'helm_sync_logs', ['source_id'], unique=False)
    op.create_table('mirror_release_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_repository_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_prerelease', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_repository_id'], ['source_repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mirror_release_logs_id'), 'mirror_release_logs', ['id'], unique=False)
    op.create_index(op.f('ix_mirror_release_logs_source_repository_id'), 'mirror_release_logs', ['source_repository_id'], unique=False)
    op.create_table('pipeline_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('overrides', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['gitlab_components.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_components_id'), 'pipeline_components', ['id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('gitlab_project_id', sa.Integer(), nullable=False),
    sa.Column('gitlab_pipeline_id', sa.Integer(), nullable=True),
    sa.Column('pipeline_id', sa.Integer(), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=True),
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('status_flag', sa.Integer(), nullable=False),
    sa.Column('status_text', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('web_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['gitlab_components.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['resource_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_component_id'), 'pipeline_runs', ['component_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_id'), 'pipeline_runs', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_pipeline_id'), 'pipeline_runs', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_provider_id'), 'pipeline_runs', ['provider_id'], unique=False)
    op.create_table('sync_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pipeline_id', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('sync_cron', sa.String(length=100), nullable=True),
    sa.Column('sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('sync_concurrency', sa.Integer(), nullable=False),
    sa.Column('freshness_cron', sa.String(length=100), nullable=True),
    sa.Column('freshness_enabled', sa.Boolean(), nullable=False),
    sa.Column('freshness_concurrency', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_groups_id'), 'sync_groups', ['id'], unique=False)
    op.create_index(op.f('ix_sync_groups_name'), 'sync_groups', ['name'], unique=True)
    op.create_table('sync_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sa.String(length=20), nullable=False),
    sa.Column('docker_image_source_id', sa.Integer(), nullable=True),
    sa.Column('helm_chart_source_id', sa.Integer(), nullable=True),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('use_default_schedule', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(docker_image_source_id IS NOT NULL AND helm_chart_source_id IS NULL) OR (docker_image_source_id IS NULL AND helm_chart_source_id IS NOT NULL)', name='chk_sync_schedule_only_one_fk'),
    sa.ForeignKeyConstraint(['docker_image_source_id'], ['docker_image_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['helm_chart_source_id'], ['helm_chart_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_schedules_docker_image_source_id'), 'sync_schedules', ['docker_image_source_id'], unique=False)
    op.create_index(op.f('ix_sync_schedules_helm_chart_source_id'), 'sync_schedules', ['helm_chart_source_id'], unique=False)
    op.create_index(op.f('ix_sync_schedules_id'), 'sync_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_sync_schedules_sync_type'), 'sync_schedules', ['sync_type'], unique=False)
    op.create_table('mirrors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_repository_id', sa.Integer(), nullable=False),
    sa.Column('sync_group_id', sa.Integer(), nullable=True),
    sa.Column('target_namespace', sa.String(length=500), nullable=True),
    sa.Column('target_project_name', sa.String(length=255), nullable=True),
    sa.Column('target_project_id', sa.String(length=255), nullable=True),
    sa.Column('target_web_url', sa.String(length=500), nullable=True),
    sa.Column('status_flag', sa.Integer(), nullable=False),
    sa.Column('status_text', sa.String(length=500), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=50), nullable=True),
    sa.Column('last_freshness_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_freshness_status', sa.String(length=50), nullable=True),
    sa.Column('last_known_commit_sha', sa.String(length=40), nullable=True),
    sa.Column('last_known_commit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_known_commit_author', sa.String(length=255), nullable=True),
    sa.Column('target_diverged_commits', sa.Integer(), nullable=False),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_repository_id'], ['source_repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sync_group_id'], ['sync_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mirrors_id'), 'mirrors', ['id'], unique=False)
    op.create_table('role_scope_sync_groups',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('sync_group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sync_group_id'], ['sync_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'sync_group_id')
    )
    op.create_table('mirror_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mirror_id', sa.Integer(), nullable=False),
    sa.Column('log_type', sa.Enum('sync', 'freshness', 'import_', 'integrity', name='mirror_log_type_enum'), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=True),
    sa.Column('gitlab_pipeline_id', sa.String(length=255), nullable=True),
    sa.Column('gitlab_pipeline_url', sa.String(length=500), nullable=True),
    sa.Column('status_flag', sa.Integer(), nullable=False),
    sa.Column('status_text', sa.String(length=500), nullable=True),
    sa.Column('source_commit_sha', sa.String(length=40), nullable=True),
    sa.Column('source_commit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_commit_sha', sa.String(length=40), nullable=True),
    sa.Column('commits_behind', sa.Integer(), nullable=True),
    sa.Column('target_extra_commits', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mirror_id'], ['mirrors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mirror_logs_id'), 'mirror_logs', ['id'], unique=False)
    op.create_index(op.f('ix_mirror_logs_mirror_id'), 'mirror_logs', ['mirror_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mirror_logs_mirror_id'), table_name='mirror_logs')
    op.drop_index(op.f('ix_mirror_logs_id'), table_name='mirror_logs')
    op.drop_table('mirror_logs')
    op.drop_table('role_scope_sync_groups')
    op.drop_index(op.f('ix_mirrors_id'), table_name='mirrors')
    op.drop_table('mirrors')
    op.drop_index(op.f('ix_sync_schedules_sync_type'), table_name='sync_schedules')
    op.drop_index(op.f('ix_sync_schedules_id'), table_name='sync_schedules')
    op.drop_index(op.f('ix_sync_schedules_helm_chart_source_id'), table_name='sync_schedules')
    op.drop_index(op.f('ix_sync_schedules_docker_image_source_id'), table_name='sync_schedules')
    op.drop_table('sync_schedules')
    op.drop_index(op.f('ix_sync_groups_name'), table_name='sync_groups')
    op.drop_index(op.f('ix_sync_groups_id'), table_name='sync_groups')
    op.drop_table('sync_groups')
    op.drop_index(op.f('ix_pipeline_runs_provider_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_pipeline_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_component_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_pipeline_components_id'), table_name='pipeline_components')
    op.drop_table('pipeline_components')
    op.drop_index(op.f('ix_mirror_release_logs_source_repository_id'), table_name='mirror_release_logs')
    op.drop_index(op.f('ix_mirror_release_logs_id'), table_name='mirror_release_logs')
    op.drop_table('mirror_release_logs')
    op.drop_index(op.f('ix_helm_sync_logs_source_id'), table_name='helm_sync_logs')
    op.drop_index(op.f('ix_helm_sync_logs_id'), table_name='helm_sync_logs')
    op.drop_table('helm_sync_logs')
    op.drop_index(op.f('ix_helm_chart_versions_source_id'), table_name='helm_chart_versions')
    op.drop_index(op.f('ix_helm_chart_versions_id'), table_name='helm_chart_versions')
    op.drop_index(op.f('ix_helm_chart_versions_chart_name'), table_name='helm_chart_versions')
    op.drop_table('helm_chart_versions')
    op.drop_index(op.f('ix_docker_sync_logs_source_id'), table_name='docker_sync_logs')
    op.drop_index(op.f('ix_docker_sync_logs_id'), table_name='docker_sync_logs')
    op.drop_table('docker_sync_logs')
    op.drop_index(op.f('ix_docker_image_tags_source_id'), table_name='docker_image_tags')
    op.drop_index(op.f('ix_docker_image_tags_image_name'), table_name='docker_image_tags')
    op.drop_index(op.f('ix_docker_image_tags_id'), table_name='docker_image_tags')
    op.drop_table('docker_image_tags')
    op.drop_index(op.f('ix_build_logs_image_version_id'), table_name='build_logs')
    op.drop_index(op.f('ix_build_logs_id'), table_name='build_logs')
    op.drop_table('build_logs')
    op.drop_index(op.f('ix_source_repositories_provider_id'), table_name='source_repositories')
    op.drop_index(op.f('ix_source_repositories_id'), table_name='source_repositories')
    op.drop_table('source_repositories')
    op.drop_table('role_scope_providers')
    op.drop_index(op.f('ix_pipelines_provider_id'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_name'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_is_deleted'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_id'), table_name='pipelines')
    op.drop_table('pipelines')
    op.drop_index(op.f('ix_image_versions_image_type'), table_name='image_versions')
    op.drop_index(op.f('ix_image_versions_id'), table_name='image_versions')
    op.drop_index(op.f('ix_image_versions_gold_image_id'), table_name='image_versions')
    op.drop_index(op.f('ix_image_versions_app_image_id'), table_name='image_versions')
    op.drop_table('image_versions')
    op.drop_index(op.f('ix_helm_chart_sources_provider_id'), table_name='helm_chart_sources')
    op.drop_index(op.f('ix_helm_chart_sources_name'), table_name='helm_chart_sources')
    op.drop_index(op.f('ix_helm_chart_sources_id'), table_name='helm_chart_sources')
    op.drop_table('helm_chart_sources')
    op.drop_index(op.f('ix_gitlab_components_provider_id'), table_name='gitlab_components')
    op.drop_index(op.f('ix_gitlab_components_id'), table_name='gitlab_components')
    op.drop_table('gitlab_components')
    op.drop_index(op.f('ix_docker_image_sources_target_provider_id'), table_name='docker_image_sources')
    op.drop_index(op.f('ix_docker_image_sources_provider_id'), table_name='docker_image_sources')
    op.drop_index(op.f('ix_docker_image_sources_name'), table_name='docker_image_sources')
    op.drop_index(op.f('ix_docker_image_sources_id'), table_name='docker_image_sources')
    op.drop_table('docker_image_sources')
    op.drop_index(op.f('ix_build_schedules_image_type'), table_name='build_schedules')
    op.drop_index(op.f('ix_build_schedules_id'), table_name='build_schedules')
    op.drop_index(op.f('ix_build_schedules_gold_image_id'), table_name='build_schedules')
    op.drop_index(op.f('ix_build_schedules_app_image_id'), table_name='build_schedules')
    op.drop_table('build_schedules')
    op.drop_table('user_roles')
    op.drop_index('ix_team_members_user', table_name='team_members')
    op.drop_table('team_members')
    op.drop_table('role_scope_source_groups')
    op.drop_table('role_scope_credentials')
    op.drop_table('role_permissions')
    op.drop_index('uq_resource_providers_name', table_name='resource_providers', postgresql_where=sa.text('is_deleted = false'), sqlite_where=sa.text('is_deleted = false'))
    op.drop_index('uq_default_per_scope', table_name='resource_providers', postgresql_where=sa.text('is_default = true AND is_deleted = false'), sqlite_where=sa.text('is_default = true AND is_deleted = false'))
    op.drop_index('ix_resource_providers_team', table_name='resource_providers')
    op.drop_index('ix_resource_providers_owner', table_name='resource_providers')
    op.drop_index(op.f('ix_resource_providers_id'), table_name='resource_providers')
    op.drop_index('ix_resource_providers_domain_subtype', table_name='resource_providers')
    op.drop_index('ix_resource_providers_category', table_name='resource_providers')
    op.drop_table('resource_providers')
    op.drop_index(op.f('ix_github_releases_project_id'), table_name='github_releases')
    op.drop_index(op.f('ix_github_releases_id'), table_name='github_releases')
    op.drop_table('github_releases')
    op.drop_index(op.f('ix_app_images_project_id'), table_name='app_images')
    op.drop_index(op.f('ix_app_images_name'), table_name='app_images')
    op.drop_index(op.f('ix_app_images_id'), table_name='app_images')
    op.drop_index(op.f('ix_app_images_gold_image_id'), table_name='app_images')
    op.drop_table('app_images')
    op.drop_index('uq_teams_name', table_name='teams', postgresql_where=sa.text('is_deleted = false'), sqlite_where=sa.text('is_deleted = false'))
    op.drop_index('ix_teams_owner', table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_github_projects_id'), table_name='github_projects')
    op.drop_index(op.f('ix_github_projects_full_name'), table_name='github_projects')
    op.drop_table('github_projects')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_keycloak_sub'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_source_groups_id'), table_name='source_groups')
    op.drop_table('source_groups')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_oidc_config_id'), table_name='oidc_config')
    op.drop_table('oidc_config')
    op.drop_index(op.f('ix_gold_images_name'), table_name='gold_images')
    op.drop_index(op.f('ix_gold_images_id'), table_name='gold_images')
    op.drop_table('gold_images')
    op.drop_index(op.f('ix_github_orgs_login'), table_name='github_orgs')
    op.drop_index(op.f('ix_github_orgs_id'), table_name='github_orgs')
    op.drop_table('github_orgs')
    op.drop_index(op.f('ix_credentials_name'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_id'), table_name='credentials')
    op.drop_table('credentials')
    # ### end Alembic commands ###
